/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
"use client";

import { Check, Download, Moon, Sun, Upload, X } from "lucide-react";
import { useRef } from "react";
import type { WorkspaceState } from "@/src/types/workspace";
import { downloadBackup } from "@/src/utils/exporters";

export function SettingsDialog({ state, onChange, onRestore, onClose }: { state: WorkspaceState; onChange: (state: WorkspaceState) => void; onRestore: (state: WorkspaceState) => void; onClose: () => void }) {
  const inputRef = useRef<HTMLInputElement>(null);
  return <dialog open className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="settings-dialog"><div className="modal-header"><div><span className="modal-kicker">TU ESPACIO</span><h2>Preferencias</h2></div><button className="icon-button" onClick={onClose}><X /></button></div><section><h3>Apariencia</h3><div className="theme-options"><button className={state.theme === "light" ? "selected" : ""} onClick={() => onChange({ ...state, theme: "light" })}><Sun />Claro{state.theme === "light" && <Check />}</button><button className={state.theme === "dark" ? "selected" : ""} onClick={() => onChange({ ...state, theme: "dark" })}><Moon />Oscuro{state.theme === "dark" && <Check />}</button></div></section><section><h3>Color de acento</h3><div className="accent-options">{["#5676e8", "#7c5ce5", "#d86568", "#1a9c78", "#d18431"].map((color) => <button key={color} style={{ background: color }} className={state.accent === color ? "selected" : ""} onClick={() => onChange({ ...state, accent: color })} aria-label={`Color ${color}`}>{state.accent === color && <Check />}</button>)}</div></section><section><h3>Ancho del documento</h3><div className="segmented">{(["compact", "comfortable", "wide"] as const).map((width) => <button key={width} className={state.documentWidth === width ? "selected" : ""} onClick={() => onChange({ ...state, documentWidth: width })}>{width === "compact" ? "Compacto" : width === "comfortable" ? "Cómodo" : "Amplio"}</button>)}</div></section><section><h3>Datos locales</h3><p>Tus documentos viven en este dispositivo. Crea una copia portable cuando quieras.</p><div className="backup-actions"><button onClick={() => downloadBackup(state)}><Download /> Crear copia</button><button onClick={() => inputRef.current?.click()}><Upload /> Restaurar</button><input ref={inputRef} hidden type="file" accept="application/json" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { const payload = JSON.parse(await file.text()) as { format?: string; state?: WorkspaceState }; if (payload.format === "lumina-workspace" && payload.state && window.confirm("Esta acción reemplazará el espacio actual. ¿Continuar?")) { onRestore(payload.state); onClose(); } else if (!payload.state) window.alert("El archivo no parece ser una copia válida de Lúmina."); } catch { window.alert("No fue posible leer la copia de seguridad."); } }} /></div></section></div></dialog>;
}
